name: Tests

on:
  push:
    branches:
      - "main"
      - "develop"
      - "release"
      - "fix/*"
      - "feature/*"
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, synchronize, closed]
    paths-ignore:
      - "**.md"

jobs:
  test-typescript:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        node-version:
          - 22
          - 24

    steps:
      - uses: actions/checkout@v4
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run test:pretty

  build:
    needs: test-typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: dist/
